# This configuration is just for development
services:
  mongo_db:
    image: mongo
    restart: unless-stopped
    container_name: modulee_mongo_db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis_db:
    image: redis
    restart: unless-stopped
    container_name: modulee_redis_db
    ports:
      - 6379:6379
