# This configuration is just for development
services:
  postgres_db:
    image: postgres
    restart: unless-stopped
    container_name: modulee_postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: modulee
      POSTGRES_PASSWORD: example
  redis_db:
    image: redis
    restart: unless-stopped
    container_name: modulee_redis_db
    ports:
      - 6379:6379
