// This object is someway similar to internationalization. It should not be
// interpreted as important to the logic of the application
//
// TODO implement real internationalization.
export const nodesName: Record<string, string> = {
	IfNode: 'If',
	OrNode: 'Or',
	NotNode: 'Not',
	AndNode: 'And',
	AddNode: 'Add',
	GateNode: 'Gate',
	TimeNode: 'Time',
	HoldNode: 'Hold',
	InputNode: 'Input',
	NoiseNode: 'Noise',
	PhaseNode: 'Phase',
	PitchNode: 'Pitch',
	DivideNode: 'Divide',
	OutputNode: 'Output',
	ModuleNode: 'Module',
	ModuloNode: 'Modulo',
	ControlNode: 'Control',
	GreaterNode: 'Greater',
	PeakNode: 'Peak filter',
	EnvelopeNode: 'Envelope',
	ConstantNode: 'Constant',
	SubtractNode: 'Subtract',
	MultiplyNode: 'Multiply',
	SineWaveNode: 'Sine wave',
	FrequencyNode: 'Frequency',
	PulseWaveNode: 'Pulse wave',
	AllPassNode: 'All-pass filter',
	LowPassNode: 'Low-pass filter',
	HighPassNode: 'High-pass filter',
	TriangleWaveNode: 'Triangle wave',
	SawtoothWaveNode: 'Sawtooth wave',
	ModuleVoicesNode: 'Module voices',
	RandomFromValueNode: 'Random from value',
};
