// This object is someway similar to internationalization. It should not be
// interpreted as important to the logic of the application
//
// TODO implement real internationalization.
export const nodesName: Record<string, string> = {
	AddNode: 'Add',
	AllPassNode: 'All-pass filter',
	AndNode: 'And',
	AudioInputNode: 'Audio input',
	ConstantNode: 'Constant',
	ControlNode: 'Control',
	DelayNode: 'Delay',
	DivideNode: 'Divide',
	EnvelopeNode: 'Envelope',
	FrequencyNode: 'Frequency',
	GateNode: 'Gate',
	GreaterNode: 'Greater',
	HighPassNode: 'High-pass filter',
	HoldNode: 'Hold',
	IfNode: 'If',
	InputNode: 'Input',
	LowPassNode: 'Low-pass filter',
	ModuleNode: 'Module',
	ModuleVoicesNode: 'Module voices',
	ModuloNode: 'Modulo',
	MultiplyNode: 'Multiply',
	NoiseNode: 'Noise',
	NotNode: 'Not',
	OrNode: 'Or',
	OutputNode: 'Output',
	PeakNode: 'Peak filter',
	PhaseNode: 'Phase',
	PitchNode: 'Pitch',
	PulseWaveNode: 'Pulse wave',
	RandomFromValueNode: 'Random from value',
	SawtoothWaveNode: 'Sawtooth wave',
	SineWaveNode: 'Sine wave',
	SubtractNode: 'Subtract',
	TimeNode: 'Time',
	TriangleWaveNode: 'Triangle wave',
	ValueFromChannelNode: 'Value from channel',
};
